### ISSUE TITLE
테스트 화면

### ISSUE THREAD

**Issue by sieunju** [sieunju/httptracking#18]
![스크린샷 2022-05-03 오전 9 50 16](https://user-images.githubusercontent.com/33802191/166390208-4d42dbcc-b082-4f9f-94d4-4afc13901eb1.png)

![스크린샷 2022-05-03 오전 9 50 31](https://user-images.githubusercontent.com/33802191/166390217-ede0ee13-8b79-4c30-b603-0814b4f0f92e.png)

![스크린샷 2022-05-03 오전 9 50 53](https://user-images.githubusercontent.com/33802191/166390225-a0a1ad62-4855-4435-90c0-720585752bc8.png)

**Comment by audrl1010** [comment]
path 검색 기능도 있으면 짱짱 맨일 것 같아요 ~ :)

**Comment by sieunju** [comment]
오! 좋은 생각 같습니다. 
아니면 패스 필터로 하는것도 괜찮아 보입니다.
