### ISSUE TITLE
Release Build Error

### ISSUE THREAD

**Issue by sieunju** [sieunju/httptracking#57]
**Please complete the following information:**
- Library Version [e.g. com.github.sieunju.httptracking:ui:1.2.0]
- Affected Device(s) [e.g. Android 13.0]
 
**Describe the Bug:**
Fatal Exception: java.lang.NoSuchFieldError
No static field INVALID_FIELD_OFFSET of type I in class Lsun/misc/Unsafe; or its superclasses (declaration of ‘sun.misc.Unsafe’ appears in /apex/com.android.art/javalib/core-oj.jar)

Add a clear description about the problem.

**Expected Behavior:**

A clear description of what you expected to happen.

**Comment by sieunju** [comment]
closed 1.2.1-beta01 
https://github.com/sieunju/httptracking/releases/tag/1.2.1-beta01

**Comment by audrl1010** [comment]
👍
